from enum import StrEnum


class DegradationMode(StrEnum):
    NORMAL = 'NORMAL'
    DEGRADED = 'DEGRADED'
    AI_OFFLINE = 'AI_OFFLINE'
    COMMS_LIMITED = 'COMMS_LIMITED'
    LOCAL_ONLY = 'LOCAL_ONLY'
    NAV_LIMITED = 'NAV_LIMITED'
    RECORD_ONLY = 'RECORD_ONLY'
    UNSAFE_STORAGE = 'UNSAFE_STORAGE'
    ABORT_REQUIRED = 'ABORT_REQUIRED'

